#!/usr/bin/env python3
"""Build tools/denylist.txt from a real receipt's text, without printing any of it.

The denylist is the last line of the PII scanner's defence: literal strings that
must never appear anywhere in this repository. Typing your loyalty number or home
address into a terminal to populate it is exactly the moment it ends up in shell
history. So this reads the values out of a text file you point it at (OCR text of
a real receipt, a retailer export, or a hand-written list) and writes them to the
gitignored denylist. It prints counts and categories only.

    python3 -m tools.build_denylist path/to/receipt.txt
    python3 -m tools.build_denylist --coords 34.1234 -118.1234   # a home base

Coordinates are stored as prefixes to three decimals (a band about 110 m wide),
so that any file containing a coordinate that close to home is flagged.
Values merge with what is already in the file.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "tools" / "denylist.txt"

MIN_LENGTH = 6

EMAIL = re.compile(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b")
PHONE = re.compile(r"(?<!\d)(?:\+?1[-. ]?)?\(?\d{3}\)?[-. ]?\d{3}[-. ]?\d{4}(?!\d)")
DIGIT_RUN = re.compile(r"(?<![\d.])\d{9,20}(?![\d.])")
STREET = re.compile(
    r"\b\d{1,6}\s+(?:[A-Z][A-Za-z.'-]*\s+){0,4}"
    r"(?:St|Street|Ave|Avenue|Rd|Road|Blvd|Boulevard|Ln|Lane|Dr|Drive|Ct|Court|Way|Pl|"
    r"Place|Ter|Terrace|Cir|Circle|Hwy|Highway|Pkwy|Parkway|Trl|Trail|Loop|Row|Walk|"
    r"Mews|Crescent|Alley|Grove)\b\.?"
)
ZIP_PLUS_FOUR = re.compile(r"(?<!\d)\d{5}-\d{4}(?!\d)")
MASKED_CARD = re.compile(r"[*Xx#]{4,}[ -]?\d{4}\b")


def is_ignored(path: Path) -> bool:
    result = subprocess.run(
        ["git", "check-ignore", "-q", str(path)],
        cwd=REPO_ROOT,
        capture_output=True,
        check=False,
    )
    return result.returncode == 0


def harvest(text: str) -> dict[str, set[str]]:
    found: dict[str, set[str]] = {
        "email": set(),
        "phone": set(),
        "digit_run": set(),
        "street": set(),
        "zip_plus_four": set(),
        "masked_card": set(),
    }
    found["email"].update(m.lower() for m in EMAIL.findall(text))
    found["phone"].update(re.sub(r"\D", "", m) for m in PHONE.findall(text))
    found["digit_run"].update(DIGIT_RUN.findall(text))
    found["street"].update(m.strip().lower() for m in STREET.findall(text))
    found["zip_plus_four"].update(ZIP_PLUS_FOUR.findall(text))
    found["masked_card"].update(m[-4:] for m in MASKED_CARD.findall(text))
    return {
        k: {v for v in vs if len(v) >= MIN_LENGTH or k == "masked_card"}
        for k, vs in found.items()
    }


def coordinate_prefixes(lat: float, lon: float) -> set[str]:
    return {f"{lat:.3f}", f"{lon:.3f}"}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("paths", nargs="*", type=Path, help="text files to harvest")
    parser.add_argument(
        "--coords",
        nargs=2,
        type=float,
        action="append",
        metavar=("LAT", "LON"),
        help="a home or habitual location to protect; may be repeated",
    )
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)

    if not is_ignored(args.output):
        print(f"refusing to write {args.output}: it is not gitignored", file=sys.stderr)
        return 2

    entries: set[str] = set()
    counts: Counter[str] = Counter()
    for path in args.paths:
        text = path.read_text(encoding="utf-8", errors="replace")
        for kind, values in harvest(text).items():
            counts[kind] += len(values)
            entries.update(values)
    for lat, lon in args.coords or []:
        prefixes = coordinate_prefixes(lat, lon)
        counts["coordinate_prefix"] += len(prefixes)
        entries.update(prefixes)

    existing: set[str] = set()
    if args.output.exists():
        for raw in args.output.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if line and not line.startswith("#"):
                existing.add(line.lower())
    merged = sorted(existing | {e.lower() for e in entries})
    header = (
        "# Literal strings that must never appear in this repository.\n"
        "# Generated by tools/build_denylist.py. This file is gitignored. Do not commit it.\n"
    )
    args.output.write_text(header + "\n".join(merged) + "\n", encoding="utf-8")

    print(f"denylist: {len(merged)} entries ({len(merged) - len(existing)} new)")
    for kind, n in sorted(counts.items()):
        print(f"  {kind}: {n}")

    # The committed digests are derived from this file, so regenerate them here
    # rather than leaving the two to drift until CI notices.
    if args.output == DEFAULT_OUTPUT:
        from tools.denylist import create_salt, write_hashes

        count, lengths = write_hashes(merged, create_salt())
        print(f"  digests: {count} over {lengths} length(s) -> tools/denylist.hashes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
